# Generated by Django 5.1.4 on 2025-06-05 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailotp_customuser_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
